### PR TITLE
Patch: avformat/webvttdec: Ignore REGION and STYLE chunks

### PR DESCRIPTION
**Pull request by tpikonen**
This patch fixes WebVTT subtitle decoding.

### CODE REVIEW

**Comment by tpikonen** [comment]
I did not check if this actually builds, so setting as draft for now.

**Comment by pukkandan** [comment]
Related: https://github.com/yt-dlp/yt-dlp/issues/3622#issuecomment-1159791613, https://github.com/yt-dlp/yt-dlp/issues/4127

**Comment by nihil-admirari** [comment]
1. Too many unrelated changes, please rebase on top of `master`. Unfortunately, because of continuous automatic rebase, this step may have to be repeated multiple times.
2. Please fill in the README.
3. You patch is present in the mailing list: https://ffmpeg.org/pipermail/ffmpeg-devel/2022-May/296353.html, but I was unable to find it in Patchwork: https://patchwork.ffmpeg.org/project/ffmpeg/list/?q=webvttdec. Probably makes sense to resubmit.
4. Have you tried to ping the devs in IRC?

**Comment by tpikonen** [comment]
Thanks @nihil-admirari, I did not know about the ffmpeg patchwork before. In the patchwork link you provided, I counted 4 patches claiming to fix the same problem as this patch, some of them several years old. I don't think adding a fifth one helps.

I don't use these builds myself, so I'm not going to do any more work to get this patch in, but please do include it, if you find it useful.

**Comment by nihil-admirari** [comment]
> I don't use these builds myself, so I'm not going to do any more work to get this patch in, but please do include it, if you find it useful.
Ok, I'll do.

> I counted 4 patches claiming to fix the same problem as this patch, some of them several years old. I don't think adding a fifth one helps.
Can you please provide the links to these patches? I'll ask FFmpeg devs why they haven't been merged yet.

**Comment by tpikonen** [comment]
> Can you please provide the links to these patches? I'll ask FFmpeg devs why they haven't been merged yet.

- avformat/webvttdec: skip STYLE blocks https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210907153840.118561-1-sth.dev@tejp.de/
- avformat/webvttdec: Fix WebVTT decoder truncating files at first STYLE block https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210112164937.7219-1-roderich.schupp@gmail.com/
- lavf/webvttdec: ignore unrecognized blocks https://patchwork.ffmpeg.org/project/ffmpeg/patch/20200618004743.95896-5-rcombs@rcombs.me/
- avformat/webvttdec, enc: correctly process files containing STYLE, REGION blocks https://patchwork.ffmpeg.org/project/ffmpeg/patch/CA+_k4RJ1CNriPbhxxzLf1O6V1VuP2OXch3E8LqOsMNSRUyEnTw@mail.gmail.com/ (this would be the one to merge, if it works as advertised)

HTH

**Comment by nihil-admirari** [comment]
https://patchwork.ffmpeg.org/project/ffmpeg/patch/CA+_k4RJ1CNriPbhxxzLf1O6V1VuP2OXch3E8LqOsMNSRUyEnTw@mail.gmail.com/ is the only patch with tests; unfortunately they fail, and that's probably why it hasn't been merged.

**Comment by gamer191** [comment]
> https://patchwork.ffmpeg.org/project/ffmpeg/patch/CA+_k4RJ1CNriPbhxxzLf1O6V1VuP2OXch3E8LqOsMNSRUyEnTw@mail.gmail.com/ is the only patch with tests

wdym? ~~They all have tests~~, and the tests for the first two patches passed. The third one's tests are stuck on pending, and the 4th one fails (as you know)

EDIT: never mind, I misunderstood you

**Comment by pukkandan** [comment]
@nihil-admirari Thanks for dealing with this!

**Pull request merged**
