### PR TITLE
Windows long path support

### PR DESCRIPTION
**Pull request by nihil-admirari**

### CODE REVIEW

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/FFmpeg-Builds/commit/6ce9d9e00970051eecc81ffa18e0685b82c2c945

**Comment by pukkandan** [comment]
@nihil-admirari Please have a look at the build failure. I disabled 4.4 builds, but we cant disable master builds

**Comment by pukkandan** [comment]
nvm, it's because the vp9 patch has finally been merged upstream 😮

**Comment by nihil-admirari** [comment]
```
2022-02-13T14:03:37.9560300Z Applying /patches/0001-Fixes-ticket-9086.patch
2022-02-13T14:03:37.9561452Z + echo 'Applying /patches/0001-Fixes-ticket-9086.patch'
2022-02-13T14:03:37.9561942Z + git apply /patches/0001-Fixes-ticket-9086.patch
2022-02-13T14:03:37.9578373Z error: patch failed: fftools/ffmpeg.c:823
2022-02-13T14:03:37.9578873Z error: fftools/ffmpeg.c: patch does not apply
```

I talked FFmpeg dev into merging Danny Wu's patch, so it no longer applies. See https://github.com/ytdl-org/youtube-dl/issues/28042#issuecomment-1038156783.

**Comment by pukkandan** [comment]
ironic that we added a new patch just as this repo was about to become redundant 😄

**Comment by nihil-admirari** [comment]
https://github.com/yt-dlp/FFmpeg-Builds/pull/18 backports the fix from `master` to release branches just like https://github.com/yt-dlp/FFmpeg-Builds/pull/2 once did.

**Comment by LuminairPrime** [comment]
> ```
> 2022-02-13T14:03:37.9560300Z Applying /patches/0001-Fixes-ticket-9086.patch
> 2022-02-13T14:03:37.9561452Z + echo 'Applying /patches/0001-Fixes-ticket-9086.patch'
> 2022-02-13T14:03:37.9561942Z + git apply /patches/0001-Fixes-ticket-9086.patch
> 2022-02-13T14:03:37.9578373Z error: patch failed: fftools/ffmpeg.c:823
> 2022-02-13T14:03:37.9578873Z error: fftools/ffmpeg.c: patch does not apply
> ```
> 
> I talked FFmpeg dev into merging Danny Wu's patch, so it no longer applies. See [ytdl-org/youtube-dl#28042 (comment)](https://github.com/ytdl-org/youtube-dl/issues/28042#issuecomment-1038156783).

Well done all, thank you for getting this done, and sorry for the trouble with the ffmpeg org!

**Pull request closed without merging**
